name: infra-deploy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'Create Resource Group'
        run: az group create -n capp-demo-techsummit -l westeurope

      - name: 'Deploy infra'
        working-directory: ./bicep
        run: |
          az bicep build -f ./main.bicep
          az deployment group create -g capp-demo-techsummit -f ./main.json
